server.port=8081
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/idreamdb?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
student.service.url=${STUDENT_SERVICE_URL:http://localhost:8082}
management.endpoints.web.exposure.include=health,info
